// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: example/example.proto

package main

import (
	_ "github.com/protoc-gen/protoc-gen-go-errors/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientError int32

const (
	ClientError_BAD_REQUEST               ClientError = 0
	ClientError_USER_NOT_FOUND            ClientError = 1
	ClientError_USER_ALREADY_EXISTS       ClientError = 2
	ClientError_INVALID_EMAIL_OR_PASSWORD ClientError = 3
	ClientError_PROVIDER_NOT_SUPPORTED    ClientError = 4
)

// Enum value maps for ClientError.
var (
	ClientError_name = map[int32]string{
		0: "BAD_REQUEST",
		1: "USER_NOT_FOUND",
		2: "USER_ALREADY_EXISTS",
		3: "INVALID_EMAIL_OR_PASSWORD",
		4: "PROVIDER_NOT_SUPPORTED",
	}
	ClientError_value = map[string]int32{
		"BAD_REQUEST":               0,
		"USER_NOT_FOUND":            1,
		"USER_ALREADY_EXISTS":       2,
		"INVALID_EMAIL_OR_PASSWORD": 3,
		"PROVIDER_NOT_SUPPORTED":    4,
	}
)

func (x ClientError) Enum() *ClientError {
	p := new(ClientError)
	*p = x
	return p
}

func (x ClientError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientError) Descriptor() protoreflect.EnumDescriptor {
	return file_example_example_proto_enumTypes[0].Descriptor()
}

func (ClientError) Type() protoreflect.EnumType {
	return &file_example_example_proto_enumTypes[0]
}

func (x ClientError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientError.Descriptor instead.
func (ClientError) EnumDescriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{0}
}

type UnauthorizedError int32

const (
	UnauthorizedError_UNAUTHORIZED  UnauthorizedError = 0
	UnauthorizedError_INVALID_TOKEN UnauthorizedError = 1
	UnauthorizedError_TOKEN_EXPIRED UnauthorizedError = 2
)

// Enum value maps for UnauthorizedError.
var (
	UnauthorizedError_name = map[int32]string{
		0: "UNAUTHORIZED",
		1: "INVALID_TOKEN",
		2: "TOKEN_EXPIRED",
	}
	UnauthorizedError_value = map[string]int32{
		"UNAUTHORIZED":  0,
		"INVALID_TOKEN": 1,
		"TOKEN_EXPIRED": 2,
	}
)

func (x UnauthorizedError) Enum() *UnauthorizedError {
	p := new(UnauthorizedError)
	*p = x
	return p
}

func (x UnauthorizedError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnauthorizedError) Descriptor() protoreflect.EnumDescriptor {
	return file_example_example_proto_enumTypes[1].Descriptor()
}

func (UnauthorizedError) Type() protoreflect.EnumType {
	return &file_example_example_proto_enumTypes[1]
}

func (x UnauthorizedError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnauthorizedError.Descriptor instead.
func (UnauthorizedError) EnumDescriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{1}
}

type ServerError int32

const (
	ServerError_INTERNAL_SERVER_ERROR ServerError = 0
)

// Enum value maps for ServerError.
var (
	ServerError_name = map[int32]string{
		0: "INTERNAL_SERVER_ERROR",
	}
	ServerError_value = map[string]int32{
		"INTERNAL_SERVER_ERROR": 0,
	}
)

func (x ServerError) Enum() *ServerError {
	p := new(ServerError)
	*p = x
	return p
}

func (x ServerError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerError) Descriptor() protoreflect.EnumDescriptor {
	return file_example_example_proto_enumTypes[2].Descriptor()
}

func (ServerError) Type() protoreflect.EnumType {
	return &file_example_example_proto_enumTypes[2]
}

func (x ServerError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerError.Descriptor instead.
func (ServerError) EnumDescriptor() ([]byte, []int) {
	return file_example_example_proto_rawDescGZIP(), []int{2}
}

var File_example_example_proto protoreflect.FileDescriptor

var file_example_example_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x78, 0x65, 0x72, 0x72, 0x1a, 0x13, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2a, 0x8d, 0x01, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53,
	0x54, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f,
	0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x53, 0x45, 0x52, 0x5f,
	0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x53, 0x10, 0x02,
	0x12, 0x1d, 0x0a, 0x19, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x45, 0x4d, 0x41, 0x49,
	0x4c, 0x5f, 0x4f, 0x52, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x03, 0x12,
	0x1a, 0x0a, 0x16, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f,
	0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x04, 0x1a, 0x05, 0x80, 0x88, 0x27,
	0x90, 0x03, 0x2a, 0x52, 0x0a, 0x11, 0x55, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x65, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x41, 0x55, 0x54,
	0x48, 0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x5f, 0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d,
	0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x02, 0x1a,
	0x05, 0x80, 0x88, 0x27, 0x91, 0x03, 0x2a, 0x2f, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x15, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41,
	0x4c, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00,
	0x1a, 0x05, 0x80, 0x88, 0x27, 0xf4, 0x03, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2d, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x3b, 0x6d, 0x61,
	0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_example_example_proto_rawDescOnce sync.Once
	file_example_example_proto_rawDescData = file_example_example_proto_rawDesc
)

func file_example_example_proto_rawDescGZIP() []byte {
	file_example_example_proto_rawDescOnce.Do(func() {
		file_example_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_example_proto_rawDescData)
	})
	return file_example_example_proto_rawDescData
}

var file_example_example_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_example_example_proto_goTypes = []interface{}{
	(ClientError)(0),       // 0: xerr.ClientError
	(UnauthorizedError)(0), // 1: xerr.UnauthorizedError
	(ServerError)(0),       // 2: xerr.ServerError
}
var file_example_example_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_example_proto_init() }
func file_example_example_proto_init() {
	if File_example_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_example_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_example_proto_goTypes,
		DependencyIndexes: file_example_example_proto_depIdxs,
		EnumInfos:         file_example_example_proto_enumTypes,
	}.Build()
	File_example_example_proto = out.File
	file_example_example_proto_rawDesc = nil
	file_example_example_proto_goTypes = nil
	file_example_example_proto_depIdxs = nil
}
